Repository HephaestusProject/template, pull requests merged in 2020-07, with the labels that each got.

#3 feat: Issue, PR 템플릿 작성 & GitHub Action 추가
  .github/ISSUE_TEMPLATE/README.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/paper.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yaml
Labels: enhancement

#4 feat: Issue, PR 템플릿 작성 & GitHub Action 추가 (#3)
  .github/ISSUE_TEMPLATE/README.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/paper.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yaml
Labels: enhancement

#7 Feature/#1
  README.md
Labels: enhancement

#17 feat: black 적용 후, commit/push 자동화하는 GitHub Action 추가
  .github/workflows/auto-black.yaml
Labels: enhancement

#16 feat: isort GitHub Action 및 테스트 적용
  .github/workflows/isort.yaml
Labels: enhancement

#20 feature/#11-pytest
  .github/workflows/pytest.yaml
  .gitignore
  pytest_sample.py
  requirements.txt
  tests/__init__.py
  tests/test_sample.py
Labels: enhancement

#21 refactor: pytest / isort / black action을 하나의 action파일로 통합
  .github/workflows/auto-black.yaml
  .github/workflows/isort.yaml
  .github/workflows/pytest.yaml
  .github/workflows/test.yaml
Labels: enhancement

#22 중간결과 `Master`브랜치에 병합
  .github/workflows/test.yaml
  .gitignore
  pytest_sample.py
  requirements.txt
  tests/__init__.py
  tests/test_sample.py
Labels: enhancement

#26 Test codecov
  lib/operation.py
  tests/test_operation.py
Labels: enhancement

#27 README badge작업 결과 병합
  .github/workflows/test.yaml
  README.md
  apply.sh
  lib/operation.py
  pytest_sample.py
  tests/__init__.py
  tests/test_operation.py
  tests/test_sample.py
Labels: enhancement

#28 fix: Github Action push 에러 수정
  .coverage
  .github/workflows/test.yaml
  coverage.xml
  lib/operation.py
  tests/test_operation.py
Labels: bug

#29 coverage.xml 파일 삭제 및 .gitignore 등록
  .coverage
  .gitignore
  coverage.xml
Labels: bug

#30 Push action 수정 및 coverage.xml 파일 제거 및 .gitignore 등록
  .coverage
  .github/workflows/test.yaml
  .gitignore
  lib/operation.py
  tests/test_operation.py
Labels: bug

#34 feat: template structure 설정
  .gitignore
  README.md
  conf/dataset/your_dataset.yml
  conf/model/your_model.yml
  evaluate.py
  infer.py
  lib/operation.py
  src/data.py
  src/metric.py
  src/model/net.py
  src/model/ops.py
  src/utils.py
  tests/__init__.py
  tests/test_ops.py
  train.py
Labels: enhancement

#35 Feature/#33
  tests/test_ops.py
Labels: hotfix

#36 feat: code style "Black" badge 추가
  README.md
Labels: enhancement

#39 Add LICENSE
  LICENSE
  README.md
Labels: enhancement

#42 feat: Mention Notifier 추가
  .github/mention-to-slack.yml
  .github/workflows/mention-to-slack.yaml
Labels: enhancement

#37 `env`에 `master`브랜치 병합
  .github/mention-to-slack.yml
  .github/workflows/lint.yaml
  .github/workflows/mention-to-slack.yaml
  .gitignore
  LICENSE
  README.md
  conf/dataset/your_dataset.yml
  conf/model/your_model.yml
  evaluate.py
  infer.py
  lib/operation.py
  src/data.py
  src/metric.py
  src/model/net.py
  src/model/ops.py
  src/utils.py
  tests/__init__.py
  tests/test_ops.py
  train.py
Labels: enhancement

#44 Hotfix/#43
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
Labels: hotfix

#45 env에 현재 master merge
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
Labels: hotfix

#47 feat: issue/paper/feature issue template 수정
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/paper.md
  utils/collect_env.py
Labels: enhancement

#50 feat: Lint action 트리거를 push로 변경
  .github/workflows/lint.yaml
Labels: enhancement

#48 feat: pytorch seed 고정 예시 추가
  evaluate.py
  infer.py
  requirements.txt
  tests/test_ops.py
  train.py
Labels: enhancement

#51 update 내용 `env` 병합
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/paper.md
  .github/workflows/lint.yaml
  evaluate.py
  infer.py
  requirements.txt
  tests/test_ops.py
  train.py
  utils/collect_env.py
Labels: enhancement

#52 feat: mention to slack 멤버 추가
  .github/mention-to-slack.yml
Labels: enhancement

#55 fix: env push error 수정
  .github/workflows/lint.yaml
Labels: enhancement

#54 mention to slack 멤버 추가
  .github/mention-to-slack.yml
  .github/workflows/lint.yaml
Labels: enhancement
